### ISSUE TITLE
APK Installation Failed

### ISSUE THREAD

**Issue by EpicJosch** [ClassicBrawlTeam/BrawlStars-v30#4]
The APK Installation failed with the error: INSTALL_PARSE_FAILED_NO_CERTIFICATES

How can i fix this?

**Comment by ShockWave5158** [comment]
Hi! Could you please tell me you Android version and device model?

**Comment by EpicJosch** [comment]
Hi, thanks for the reply. I fixed it on my own. I just installed the app "Apk Signer" from Google Play and signed the Apk.

**Comment by ShockWave5158** [comment]
Okay 👍
